### ISSUE TITLE
Visualizing evaluations

### ISSUE THREAD

**Issue by Encrux** [sam2act/SAM2Act#7]
I ran the evaluation using this command

```bash
python eval.py \
  --model-folder runs/sam2act_rlbench \
  --eval-datafolder ./data/test \
  --tasks all \
  --eval-episodes 25 \
  --log-name test/1 \
  --device 0 \
  --headless \
  --model-name model_89.pth
```

I also tried to train on one task

```yaml
device: '0'
exp_cfg_opts: tasks put_block_back
exp_cfg_path: configs/sam2act.yaml
log_dir: runs
mvt_cfg_opts: ''
mvt_cfg_path: mvt/configs/sam2act.yaml
refresh_replay: false
with_eval: false
```

which got me a bunch of .replay files in replay_temporal_memory/replay_train/put_block_back

During setup, I ran into this issue mentioned in the readme and had to install opencv in headless mode.

```
If you get qt plugin error like qt.qpa.plugin: Could not load the Qt platform plugin "xcb" <somepath>/cv2/qt/plugins" even though it was found, try uninstalling opencv-python and installing opencv-python-headless
```

Seems like I can run the code headless, but I'd like to actually visualize the robots/replays to see what they're doing. Is this possible? (e.g. by running the .replay files or something)

thanks!
